theme: jekyll-theme-minimal
title: Abdoulaye Diack
description: Program Manager AI and ML at Google Research
url: https://adiack.github.io
github_username:  adiack
google_analytics: G-6629WV7R7N
logo: https://adiack.github.io/assets/IMG_0468.webp
show_downloads: false

