theme: jekyll-theme-minimal
title: Abdoulaye Diack
description: Program Manager AI and ML at Google Research
url: https://adiack.github.io
github_username:  adiack
google_analytics: G-6629WV7R7N
logo: https://drive.google.com/uc?id=1EKr4N5TBCs1z1USBeHrBzGVuvJVn4hu1
show_downloads: false

