theme: jekyll-theme-minimal
title: Abdoulaye Diack
description: Research Program Manager at Google AI
logo: https://lh6.googleusercontent.com/ckZVzO4NhMVdErfI8hYzC5qdYfKborLdm1FVlWMIaVDI4N2HqWetCit8AmVKwNp0omqeR71w9Lo3UrMiD5xsDXhjPSRUPv-t-cxNckSnWLkFaEwkQfVAEGEZEN1cfrhoiA=w1280
show_downloads: false
